export const ROUTES = {
  home: '/',
  contact: '/contacto',
  login: '/login',
  register: '/registro',
  medicalDirectory: '/medicos-especialidades',
  accessDenied: '/acceso-denegado',
  dashboard: '/dashboard',
  profile: '/perfil',
  users: '/usuarios',
  roles: '/roles',
  adminDoctors: '/admin-medicos',
  adminSpecialties: '/admin-especialidades',
  appointmentManagement: '/gestion-citas',
  medicalSchedule: '/agenda-medica',
  clinicalObservation: '/observacion-clinica',
  clinicalHistory: '/historial-clinico',
  requestAppointment: '/solicitar-cita',
  myAppointments: '/mis-citas',
} as const
